// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { readFileSync, existsSync } from "node:fs";
import { defineConfig } from "prisma/config";

function loadDotEnvValue(key: string): string | undefined {
  if (existsSync(".env")) {
    const contents = readFileSync(".env", "utf8");
    const match = contents.match(new RegExp(`^${key}="([^"]+)"`, "m"));
    if (match) return match[1];
  }
  return process.env[key];
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: loadDotEnvValue("DATABASE_URL"),
  },
});
