import { z } from 'zod';

export const productSchema = z.object({
  nombre: z.string().min(1).max(200),
  slug: z.string().min(1).max(150).regex(/^[a-z0-9-]+$/, 'Slug inválido'),
  categoria: z.enum(['ENERGIZADORES', 'KITS_SOLARES', 'ACCESORIOS']),
  linea: z.string().max(100).optional().default(''),
  precio: z.string().max(50).optional().default(''),
  precioNumerico: z.number().finite().nonnegative().max(1e12).optional().default(0),
  subtitulo: z.string().max(300).optional().nullable(),
  descripcion: z.string().max(5000).optional().nullable(),
  imagen_local: z.string().max(500).optional().nullable(),
  alcance: z.string().max(100).optional().nullable(),
  joules: z.string().max(100).optional().nullable(),
  voltaje: z.string().max(100).optional().nullable(),
  ideal_para: z.string().max(500).optional().nullable(),
  alimentacion: z.string().max(100).optional().nullable(),
  consumo: z.string().max(100).optional().nullable(),
  cobertura: z.string().max(100).optional().nullable(),
  energia_salida: z.string().max(100).optional().nullable(),
  voltaje_salida: z.string().max(100).optional().nullable(),
  pulsos_minuto: z.string().max(100).optional().nullable(),
  varillas_tierra: z.string().max(100).optional().nullable(),
  autonomia: z.string().max(100).optional().nullable(),
  peso: z.string().max(100).optional().nullable(),
  dimensiones: z.string().max(100).optional().nullable(),
  material: z.string().max(100).optional().nullable(),
  color: z.string().max(100).optional().nullable(),
  presentacion: z.string().max(100).optional().nullable(),
  capacidad: z.string().max(100).optional().nullable(),
  longitud: z.string().max(100).optional().nullable(),
  esMasVendido: z.boolean().optional().default(false),
  esNuevo: z.boolean().optional().default(false),
  esPopular: z.boolean().optional().default(false),
  rating: z.number().finite().min(0).max(5).optional().default(0),
  valoraciones: z.number().int().nonnegative().max(1e9).optional().default(0),
  url: z.string().max(500).optional().nullable(),
  video: z.string().max(500).optional().nullable(),
  caracteristicas: z.array(z.string().max(200)).max(30).optional().default([]),
  recomendado_para: z.array(z.string().max(100)).max(30).optional().default([]),
  imagenes: z.array(z.string().max(500)).max(12).optional().default([]),
});

export type ProductFormData = z.infer<typeof productSchema> & { id?: string };
